# Generated by Django 5.1.2 on 2024-11-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='config',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
