# Generated by Django 5.1.2 on 2024-11-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='config',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
