# Generated by Django 5.1.2 on 2024-12-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_saleevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
