# Generated by Django 5.1.2 on 2024-12-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='total_rating',
        ),
    ]
