# Generated by Django 5.1.2 on 2024-12-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address_shippingaddress_shipping_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_email',
            new_name='shipping_phone',
        ),
    ]
